version: '2'
services:
  web:
    build: .
    image: wearekick/kick-commerce-crosswater
    container_name: kick-commerce-crosswater
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www/app
      - ./scss:/var/www/scss
      - ./server.js:/var/www/server.js
    depends_on:
      - db
    command: npm run start:dev
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: D0ck3R-r00T
    volumes:
      - ./mysql/.:/docker-entrypoint-initdb.d
    expose:
      - "3306"
